### ISSUE TITLE
Support other naming conventions

### ISSUE THREAD

**Issue by keyeMyria** [javiercbk/json_to_dart#22]
It would be nice if the project could support other naming conventions. Currently it only supports camelCase but it would be helpful to allow the user to choose snake_case just like the private fields option.

**Comment by javiercbk** [comment]
The project try to stay close to the [Effective Dart's style](https://www.dartlang.org/guides/language/effective-dart/style#do-name-types-using-uppercamelcase) recommendations and camel case is the recommendation.

In fact, if you take a look at [model_generator.dart](https://github.com/javiercbk/json_to_dart/blob/master/lib/model_generator.dart#L62) which would be the "main file" of this library, you can see that the code is formatted by the `DartFormatter` which provides some extra goodies like syntax validation, etc.

If you feel very strongly about snake_case you can try the following:

1. Change the [camelCase](https://github.com/javiercbk/json_to_dart/blob/master/lib/helpers.dart#L16) function and make it return snake_case.

2. If it is working correctly by running [generate_model_example.dart](https://github.com/javiercbk/json_to_dart/blob/master/example/generate_model_example.dart) (with minimal code change you can translate your own json file)

3. If it is working correctly, undo the changes in the camelCase function, create a new function called snakeCase (in camel case because everybody loves a good irony and this project uses camelCase) and search for all the `camelCase` function calls.

4. You will have to add a new boolean parameter to the [ModelGenerator constructor](https://github.com/javiercbk/json_to_dart/blob/4a60f4fd225a7f5e3902c5f5b8e2b9748010e5b3/lib/model_generator.dart#L10) specifying if snakeCase is desired (by default it would be false). In a variable called `properCase` store either the `camelCase` or `snakeCase` function (depending on the boolean value) and replace the `camelCase` calls for a call to function stored in the variable.

5. Now you are only left with this [camelCase](https://github.com/javiercbk/json_to_dart/blob/4a60f4fd225a7f5e3902c5f5b8e2b9748010e5b3/lib/syntax.dart#L94) function call. Pass the `properCase` to the [ClassDefinition](https://github.com/javiercbk/json_to_dart/blob/4a60f4fd225a7f5e3902c5f5b8e2b9748010e5b3/lib/syntax.dart#L97) constructor, store that in an instance variable and pass that function to the [Dependency constructor](https://github.com/javiercbk/json_to_dart/blob/4a60f4fd225a7f5e3902c5f5b8e2b9748010e5b3/lib/syntax.dart#L92). That will allow you to change the last `camelCase` in favour of `properCase`.

6. And you are done, test that and if it is working create a PR. If you are feeling gracefully you can create a test and add the checkbox to the UI, but I can do that.
