### ISSUE TITLE
Provide project caveats??

### ISSUE THREAD

**Issue by steve261998** [javiercbk/json_to_dart#38]

**Comment by javiercbk** [comment]
The idea is that, by adding the new editor, caveats will appear when generating dart code. But there is currently an issue with doubles like **1.0** which the formatter is transforming to int.

That should be the only non documented caveat since I thought I solved that one, I will solve it eventually.

In the project's page you will find the full caveats list [https://github.com/javiercbk/json_to_dart](https://github.com/javiercbk/json_to_dart)
