### ISSUE TITLE
'List' is deprecated and shouldn't be used.

### ISSUE THREAD

**Issue by iqfareez** [javiercbk/json_to_dart#60]
# Warning message:
`'List' is deprecated and shouldn't be used.
Try replacing the use of the deprecated member with the replacement.`

# Generated code:
```dart
  LocationCoordinate.fromJson(Map<String, dynamic> json) {
    states = json['states'].cast<String>();
    if (json['results'] != null) {
      results = new List<Results>();
      json['results'].forEach((v) {
        results.add(new Results.fromJson(v));
      });
    }
  }
```

**Comment by javiercbk** [comment]
Hey, thanks for reporting.

I believe the best replacement would be:

```dart
// results = new List<Results>();
results = new List<Results>.empty(growable: true);
```

**Comment by iqfareez** [comment]
Thank you. Your solution works

**Comment by RaulUrtecho** [comment]
> Hey, thanks for reporting.
> 
> I believe the best replacement would be:
> 
> ```dart
> // results = new List<Results>();
> results = new List<Results>.empty(growable: true);
> ```

How about to use a literal list notation?
```
// results = new List<Results>();
results = [];
```
Also from the efective dart guide:

**DON’T use new.**
Linter rule: unnecessary_new

Dart 2 makes the new keyword optional. Even in Dart 1, its meaning was never clear because factory constructors mean a new invocation may still not actually return a new object.

The language still permits new in order to make migration less painful, but consider it deprecated and remove it from your code.

**Comment by javiercbk** [comment]
This project is all about honoring Dart's recommendations, and it seems that @RaulUrtecho [is right](https://dart.dev/guides/language/effective-dart/usage#dont-use-new).

I'll replace this with a non NEW solution shortly

**Comment by javiercbk** [comment]
It's done....sorry for taking soo long...It was a good nap though
